stages:
  - test-job

include:
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/master/pipeline-defaults.yml'

test-job:
  stage: test-job
  script:
    - echo $(date) - ${TEST_VAR}