variables:
  PROJECT_NAME: "$CI_PROJECT_NAME"
  BRANCH_NAME: "$CI_COMMIT_BRANCH"
  COMMIT: "$CI_COMMIT_SHORT_SHA"
  PROJECT_ID: "$CI_PROJECT_ID"

include:
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/Production/pipeline-defaults.yml'
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/Production/react-app-build.yml'
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/Production/terraform-jobs.yml'

stages:
  - templated-build
  - templated-deployment

app-build:
  stage: templated-build
  extends: [ .app-build ]

container-build:
  stage: templated-build
  needs: [ app-build ]
  extends: [ .container-build ]

invoke-deployment-logic:
  stage: templated-build
  # needs: [ container-build ]
  extends: [ .invoke-deployment-logic ]

plan-infrastructure:
  stage: templated-deployment
  needs: [ invoke-deployment-logic, container-build ]
  extends: [ .plan ]
