include:
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/Production/pipeline-defaults.yml'
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/Production/react-app-build.yml'
  - remote: 'https://tooling.a.cas.corp.hmrc.gov.uk/gitlab/odx-api/automation/pipeline-templates/-/raw/Production/terraform-jobs.yml'

stages:
  - templated-build
  - templated-deployment

app-build:
  stage: templated-build
  extends: [ .app-build ]

build-control-scripts:
  stage: templated-build
  extends: [ .build-control-scripts ]

dockerfile:
  stage: templated-build
  needs: [ app-build ]
  extends: [ .dockerfile ]

container-build:
  stage: templated-build
  needs: [ dockerfile ]
  extends: [ .container-build ]

plan-infrastructure:
  stage: templated-deployment
  needs: [ build-control-scripts ]
  extends: [ .plan ]

apply-infrastructure:
  stage: templated-deployment
  needs: [ plan-infrastructure, container-build ]
  extends: [ .apply ]

destroy-infrastructure:
  stage: templated-deployment
  needs: [ plan-infrastructure ]
  extends: [ .destroy ]

deploy-image:
  stage: templated-deployment
  needs: [ apply-infrastructure ]
  extends: [ .deploy-image ]
